baseURL = "https://textbooks.cs.ksu.edu/cc120"
languageCode = "en-us"
title = "K-State CC 120 Textbook"

# Change the default theme to be use when building the site with Hugo
theme = ["ksucs-hugo-theme", "plausible-hugo"]

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML", "Iframeable", "Teleprompter"]
section = [ "HTML", "Iframeable", "Teleprompter"]

[params]
  landingPageURL = "/cc120"
  description = "K-State CC 120 textbookURL"
  author = "Nathan H. Bean"
  showVisitedLinks = false
  themeVariant = "purple"
  disableLanguageSwitchingButton = true
  textbookURL = "https://textbooks.cs.ksu.edu/cc120"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Custom output format for iframes
[outputFormats]
  [outputFormats.Iframeable]
    name = "Iframeable"
    baseName = "embed"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
  [outputFormats.Teleprompter]
    name = "Teleprompter"
    baseName = "tele"
    mediaType = "text/html"
    isPlainText = false
    isHtml = true

## Plausible config
[params.plausible]
  enable = true  # Whether to enable plausible tracking
  domain = "ksucs-hugo.russfeld.me"  # Plausible "domain" name/id in your dashboard
  selfhosted_domain = "plausible.russfeld.me"